<?php

namespace DesignPattern\Demo_09;

class RedShapeDecorator extends ShapeDecorator
{
    public function __construct(Shape $shape)
    {
        parent::__construct($shape);
    }

    public function draw(): void
    {
        parent::draw(); // TODO: Change the autogenerated stub
        $this->setRedBorder($this->decoratedShape);
    }

    private function setRedBorder(Shape $shape):void
    {
        echo "Border Red Color\n";
    }
}
