#! /usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Task App', 1.0);
try {
    $pdo = new PDO("mysql:dbname=blog;host=127.0.0.1", 'root', '123456');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $exception) {
    var_dump($exception);
    exit(1);
}

$databaseAdapter = new \Acme\DatabaseAdapter($pdo);

$app->add(new \Acme\ShowCommand($databaseAdapter));
$app->add(new \Acme\AddCommand($databaseAdapter));
$app->add(new \Acme\CompleteCommand($databaseAdapter));
$app->run();
